/* Generated by Together */

public class CWayPoint {
    private string m_name;
    private double m_latitude;
    private double m_longitude;
    private wp_type m_type;

    public CWayPoint(string name, double latitude, int longitude) {
    }

    public string getName() {
    }

    public double getLatitude() {
    }

    public double getLongitude() {
    }

    public void print(int format) {
    }
}
